version: '3.8'

services:
  banking-transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # volumes:
    #   - ~/.m2:/root/.m2 # Opcional: cache local Maven para build mais rápido
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb # Configurações se não usar application.yml no jar

# Para usar o H2 persistente ou outro DB, adicionaria aqui
#  db:
#    image: ...
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=...
#    volumes:
#      - db_data:/var/lib/...
#    networks:
#      - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   db_data: